# Generated by Django 4.2.2 on 2023-06-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('taks_id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=50)),
                ('taks_details', models.TextField()),
                ('task_initial_date', models.DateField(auto_now_add=True)),
                ('task_initial_time', models.TimeField(auto_now_add=True)),
                ('taks_due_date', models.DateField()),
                ('taks_due_time', models.TimeField()),
            ],
        ),
    ]
