# Generated by Django 4.2.2 on 2023-06-15 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='taks_details',
            new_name='task_details',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='taks_due_date',
            new_name='task_due_date',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='taks_due_time',
            new_name='task_due_time',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='taks_id',
            new_name='task_id',
        ),
    ]
